// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEkSoHiwGUqTKrqM3csxrcaaHxNGCmJfA',
    appId: '1:628131412671:web:cf2181fc8db62aac71a40a',
    messagingSenderId: '628131412671',
    projectId: 'zenk-portal',
    authDomain: 'zenk-portal.firebaseapp.com',
    storageBucket: 'zenk-portal.firebasestorage.app',
    measurementId: 'G-NQEPX62LTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQMsHTmcL9krfqGBksKxIsb5mRmyroMJc',
    appId: '1:628131412671:android:09065082b671fd3571a40a',
    messagingSenderId: '628131412671',
    projectId: 'zenk-portal',
    storageBucket: 'zenk-portal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChWlYHynTR6CVpHn87NOH3GsWh__lV3iU',
    appId: '1:628131412671:ios:c996cf9d1b753e0471a40a',
    messagingSenderId: '628131412671',
    projectId: 'zenk-portal',
    storageBucket: 'zenk-portal.firebasestorage.app',
    iosBundleId: 'com.example.zenkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChWlYHynTR6CVpHn87NOH3GsWh__lV3iU',
    appId: '1:628131412671:ios:c996cf9d1b753e0471a40a',
    messagingSenderId: '628131412671',
    projectId: 'zenk-portal',
    storageBucket: 'zenk-portal.firebasestorage.app',
    iosBundleId: 'com.example.zenkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEkSoHiwGUqTKrqM3csxrcaaHxNGCmJfA',
    appId: '1:628131412671:web:9770041ac7cd6db471a40a',
    messagingSenderId: '628131412671',
    projectId: 'zenk-portal',
    authDomain: 'zenk-portal.firebaseapp.com',
    storageBucket: 'zenk-portal.firebasestorage.app',
    measurementId: 'G-95JF368NJX',
  );
}
